/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AudioPlayer: typeof import('./components/AudioPlayer.vue')['default']
    EmptyState: typeof import('./components/EmptyState.vue')['default']
    Loading: typeof import('./components/Loading.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VanButton: typeof import('vant/es')['Button']
    VanDialog: typeof import('vant/es')['Dialog']
    VanTabbar: typeof import('vant/es')['Tabbar']
    VanTabbarItem: typeof import('vant/es')['TabbarItem']
    VanToast: typeof import('vant/es')['Toast']
  }
}
